// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
//
// pkg/object methods for the models in slurm.gen.go.
package v0042

import (
	"fmt"
	"strconv"

	"k8s.io/utils/ptr"

	"github.com/SlinkyProject/slurm-client/pkg/object"
	"github.com/SlinkyProject/slurm-client/pkg/utils"
)

const ObjectTypeV0042ControllerPing object.ObjectType = "V0042ControllerPing"

func (o *V0042ControllerPing) GetType() object.ObjectType {
	return ObjectTypeV0042ControllerPing
}

func (o *V0042ControllerPing) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0042ControllerPing) DeepCopy() *V0042ControllerPing {
	return utils.Clone(o)
}

func (o *V0042ControllerPing) GetKey() object.ObjectKey {
	return object.ObjectKey(ptr.Deref(o.Hostname, ""))
}

func (o *V0042ControllerPing) SetKey(key object.ObjectKey) error {
	o.Hostname = ptr.To(string(key))
	return nil
}

var _ object.Object = (*V0042ControllerPing)(nil)

type V0042ControllerPingObjectList struct {
	Items []V0042ControllerPing
}

func (o *V0042ControllerPingObjectList) GetType() object.ObjectType {
	return ObjectTypeV0042ControllerPing
}

func (o *V0042ControllerPingObjectList) GetItems() []object.Object {
	list := make([]object.Object, len(o.Items))
	for i, item := range o.Items {
		list[i] = item.DeepCopy()
	}
	return list
}

func (o *V0042ControllerPingObjectList) AppendItem(obj object.Object) {
	item, ok := obj.(*V0042ControllerPing)
	if !ok {
		return
	}
	o.Items = append(o.Items, *item.DeepCopy())
}

func (o *V0042ControllerPingObjectList) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0042ControllerPingObjectList) DeepCopy() *V0042ControllerPingObjectList {
	out := new(V0042ControllerPingObjectList)
	out.Items = make([]V0042ControllerPing, len(o.Items))
	for i, item := range o.Items {
		out.Items[i] = *item.DeepCopy()
	}
	return out
}

var _ object.ObjectList = (*V0042ControllerPingObjectList)(nil)

const ObjectTypeV0042JobInfo object.ObjectType = "V0042JobInfo"

func (o *V0042JobInfo) GetType() object.ObjectType {
	return ObjectTypeV0042JobInfo
}

func (o *V0042JobInfo) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0042JobInfo) DeepCopy() *V0042JobInfo {
	return utils.Clone(o)
}

func (o *V0042JobInfo) GetKey() object.ObjectKey {
	return object.ObjectKey(strconv.Itoa(int(ptr.Deref(o.JobId, 0))))
}

func (o *V0042JobInfo) SetKey(key object.ObjectKey) error {
	id, err := strconv.ParseInt(string(key), 10, 32)
	if err != nil {
		return fmt.Errorf("invalid job key %q: %w", key, err)
	}
	o.JobId = ptr.To(int32(id))
	return nil
}

var _ object.Object = (*V0042JobInfo)(nil)

type V0042JobInfoObjectList struct {
	Items []V0042JobInfo
}

func (o *V0042JobInfoObjectList) GetType() object.ObjectType {
	return ObjectTypeV0042JobInfo
}

func (o *V0042JobInfoObjectList) GetItems() []object.Object {
	list := make([]object.Object, len(o.Items))
	for i, item := range o.Items {
		list[i] = item.DeepCopy()
	}
	return list
}

func (o *V0042JobInfoObjectList) AppendItem(obj object.Object) {
	item, ok := obj.(*V0042JobInfo)
	if !ok {
		return
	}
	o.Items = append(o.Items, *item.DeepCopy())
}

func (o *V0042JobInfoObjectList) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0042JobInfoObjectList) DeepCopy() *V0042JobInfoObjectList {
	out := new(V0042JobInfoObjectList)
	out.Items = make([]V0042JobInfo, len(o.Items))
	for i, item := range o.Items {
		out.Items[i] = *item.DeepCopy()
	}
	return out
}

var _ object.ObjectList = (*V0042JobInfoObjectList)(nil)

const ObjectTypeV0042Node object.ObjectType = "V0042Node"

func (o *V0042Node) GetType() object.ObjectType {
	return ObjectTypeV0042Node
}

func (o *V0042Node) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0042Node) DeepCopy() *V0042Node {
	return utils.Clone(o)
}

func (o *V0042Node) GetKey() object.ObjectKey {
	return object.ObjectKey(ptr.Deref(o.Name, ""))
}

func (o *V0042Node) SetKey(key object.ObjectKey) error {
	o.Name = ptr.To(string(key))
	return nil
}

var _ object.Object = (*V0042Node)(nil)

type V0042NodeObjectList struct {
	Items []V0042Node
}

func (o *V0042NodeObjectList) GetType() object.ObjectType {
	return ObjectTypeV0042Node
}

func (o *V0042NodeObjectList) GetItems() []object.Object {
	list := make([]object.Object, len(o.Items))
	for i, item := range o.Items {
		list[i] = item.DeepCopy()
	}
	return list
}

func (o *V0042NodeObjectList) AppendItem(obj object.Object) {
	item, ok := obj.(*V0042Node)
	if !ok {
		return
	}
	o.Items = append(o.Items, *item.DeepCopy())
}

func (o *V0042NodeObjectList) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0042NodeObjectList) DeepCopy() *V0042NodeObjectList {
	out := new(V0042NodeObjectList)
	out.Items = make([]V0042Node, len(o.Items))
	for i, item := range o.Items {
		out.Items[i] = *item.DeepCopy()
	}
	return out
}

var _ object.ObjectList = (*V0042NodeObjectList)(nil)

const ObjectTypeV0042PartitionInfo object.ObjectType = "V0042PartitionInfo"

func (o *V0042PartitionInfo) GetType() object.ObjectType {
	return ObjectTypeV0042PartitionInfo
}

func (o *V0042PartitionInfo) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0042PartitionInfo) DeepCopy() *V0042PartitionInfo {
	return utils.Clone(o)
}

func (o *V0042PartitionInfo) GetKey() object.ObjectKey {
	return object.ObjectKey(ptr.Deref(o.Name, ""))
}

func (o *V0042PartitionInfo) SetKey(key object.ObjectKey) error {
	o.Name = ptr.To(string(key))
	return nil
}

var _ object.Object = (*V0042PartitionInfo)(nil)

type V0042PartitionInfoObjectList struct {
	Items []V0042PartitionInfo
}

func (o *V0042PartitionInfoObjectList) GetType() object.ObjectType {
	return ObjectTypeV0042PartitionInfo
}

func (o *V0042PartitionInfoObjectList) GetItems() []object.Object {
	list := make([]object.Object, len(o.Items))
	for i, item := range o.Items {
		list[i] = item.DeepCopy()
	}
	return list
}

func (o *V0042PartitionInfoObjectList) AppendItem(obj object.Object) {
	item, ok := obj.(*V0042PartitionInfo)
	if !ok {
		return
	}
	o.Items = append(o.Items, *item.DeepCopy())
}

func (o *V0042PartitionInfoObjectList) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0042PartitionInfoObjectList) DeepCopy() *V0042PartitionInfoObjectList {
	out := new(V0042PartitionInfoObjectList)
	out.Items = make([]V0042PartitionInfo, len(o.Items))
	for i, item := range o.Items {
		out.Items[i] = *item.DeepCopy()
	}
	return out
}

var _ object.ObjectList = (*V0042PartitionInfoObjectList)(nil)

const ObjectTypeV0042ReservationInfo object.ObjectType = "V0042ReservationInfo"

func (o *V0042ReservationInfo) GetType() object.ObjectType {
	return ObjectTypeV0042ReservationInfo
}

func (o *V0042ReservationInfo) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0042ReservationInfo) DeepCopy() *V0042ReservationInfo {
	return utils.Clone(o)
}

func (o *V0042ReservationInfo) GetKey() object.ObjectKey {
	return object.ObjectKey(ptr.Deref(o.Name, ""))
}

func (o *V0042ReservationInfo) SetKey(key object.ObjectKey) error {
	o.Name = ptr.To(string(key))
	return nil
}

var _ object.Object = (*V0042ReservationInfo)(nil)

type V0042ReservationInfoObjectList struct {
	Items []V0042ReservationInfo
}

func (o *V0042ReservationInfoObjectList) GetType() object.ObjectType {
	return ObjectTypeV0042ReservationInfo
}

func (o *V0042ReservationInfoObjectList) GetItems() []object.Object {
	list := make([]object.Object, len(o.Items))
	for i, item := range o.Items {
		list[i] = item.DeepCopy()
	}
	return list
}

func (o *V0042ReservationInfoObjectList) AppendItem(obj object.Object) {
	item, ok := obj.(*V0042ReservationInfo)
	if !ok {
		return
	}
	o.Items = append(o.Items, *item.DeepCopy())
}

func (o *V0042ReservationInfoObjectList) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0042ReservationInfoObjectList) DeepCopy() *V0042ReservationInfoObjectList {
	out := new(V0042ReservationInfoObjectList)
	out.Items = make([]V0042ReservationInfo, len(o.Items))
	for i, item := range o.Items {
		out.Items[i] = *item.DeepCopy()
	}
	return out
}

var _ object.ObjectList = (*V0042ReservationInfoObjectList)(nil)

const ObjectTypeV0042StatsMsg object.ObjectType = "V0042StatsMsg"

func (o *V0042StatsMsg) GetType() object.ObjectType {
	return ObjectTypeV0042StatsMsg
}

func (o *V0042StatsMsg) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0042StatsMsg) DeepCopy() *V0042StatsMsg {
	return utils.Clone(o)
}

func (o *V0042StatsMsg) GetKey() object.ObjectKey {
	return ""
}

func (o *V0042StatsMsg) SetKey(key object.ObjectKey) error {
	if key != o.GetKey() {
		return fmt.Errorf("%s has a fixed key %q", o.GetType(), o.GetKey())
	}
	return nil
}

var _ object.Object = (*V0042StatsMsg)(nil)

type V0042StatsMsgObjectList struct {
	Items []V0042StatsMsg
}

func (o *V0042StatsMsgObjectList) GetType() object.ObjectType {
	return ObjectTypeV0042StatsMsg
}

func (o *V0042StatsMsgObjectList) GetItems() []object.Object {
	list := make([]object.Object, len(o.Items))
	for i, item := range o.Items {
		list[i] = item.DeepCopy()
	}
	return list
}

func (o *V0042StatsMsgObjectList) AppendItem(obj object.Object) {
	item, ok := obj.(*V0042StatsMsg)
	if !ok {
		return
	}
	o.Items = append(o.Items, *item.DeepCopy())
}

func (o *V0042StatsMsgObjectList) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0042StatsMsgObjectList) DeepCopy() *V0042StatsMsgObjectList {
	out := new(V0042StatsMsgObjectList)
	out.Items = make([]V0042StatsMsg, len(o.Items))
	for i, item := range o.Items {
		out.Items[i] = *item.DeepCopy()
	}
	return out
}

var _ object.ObjectList = (*V0042StatsMsgObjectList)(nil)
