# SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
# SPDX-License-Identifier: Apache-2.0

FROM ghcr.io/slinkyproject/slurmdbd:25.11.3-ubuntu24.04
COPY etc/ /opt/etc/slurm/
COPY entrypoint/slurmdbd.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh
ENTRYPOINT /usr/local/bin/entrypoint.sh
