// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
//
// pkg/object methods for the models in slurm.gen.go.
package v0044

import (
	"strconv"

	"k8s.io/utils/ptr"

	"github.com/SlinkyProject/slurm-client/pkg/object"
	"github.com/SlinkyProject/slurm-client/pkg/utils"
)

const ObjectTypeV0044ControllerPing object.ObjectType = "V0044ControllerPing"

func (o *V0044ControllerPing) GetType() object.ObjectType {
	return ObjectTypeV0044ControllerPing
}

func (o *V0044ControllerPing) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0044ControllerPing) DeepCopy() *V0044ControllerPing {
	return utils.Clone(o)
}

func (o *V0044ControllerPing) GetKey() object.ObjectKey {
	return object.ObjectKey(ptr.Deref(o.Hostname, ""))
}

var _ object.Object = (*V0044ControllerPing)(nil)

type V0044ControllerPingObjectList struct {
	Items []V0044ControllerPing
}

func (o *V0044ControllerPingObjectList) GetType() object.ObjectType {
	return ObjectTypeV0044ControllerPing
}

func (o *V0044ControllerPingObjectList) GetItems() []object.Object {
	list := make([]object.Object, len(o.Items))
	for i, item := range o.Items {
		list[i] = item.DeepCopy()
	}
	return list
}

func (o *V0044ControllerPingObjectList) AppendItem(obj object.Object) {
	item, ok := obj.(*V0044ControllerPing)
	if !ok {
		return
	}
	o.Items = append(o.Items, *item.DeepCopy())
}

func (o *V0044ControllerPingObjectList) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0044ControllerPingObjectList) DeepCopy() *V0044ControllerPingObjectList {
	out := new(V0044ControllerPingObjectList)
	out.Items = make([]V0044ControllerPing, len(o.Items))
	for i, item := range o.Items {
		out.Items[i] = *item.DeepCopy()
	}
	return out
}

var _ object.ObjectList = (*V0044ControllerPingObjectList)(nil)

const ObjectTypeV0044JobInfo object.ObjectType = "V0044JobInfo"

func (o *V0044JobInfo) GetType() object.ObjectType {
	return ObjectTypeV0044JobInfo
}

func (o *V0044JobInfo) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0044JobInfo) DeepCopy() *V0044JobInfo {
	return utils.Clone(o)
}

func (o *V0044JobInfo) GetKey() object.ObjectKey {
	return object.ObjectKey(strconv.Itoa(int(ptr.Deref(o.JobId, 0))))
}

var _ object.Object = (*V0044JobInfo)(nil)

type V0044JobInfoObjectList struct {
	Items []V0044JobInfo
}

func (o *V0044JobInfoObjectList) GetType() object.ObjectType {
	return ObjectTypeV0044JobInfo
}

func (o *V0044JobInfoObjectList) GetItems() []object.Object {
	list := make([]object.Object, len(o.Items))
	for i, item := range o.Items {
		list[i] = item.DeepCopy()
	}
	return list
}

func (o *V0044JobInfoObjectList) AppendItem(obj object.Object) {
	item, ok := obj.(*V0044JobInfo)
	if !ok {
		return
	}
	o.Items = append(o.Items, *item.DeepCopy())
}

func (o *V0044JobInfoObjectList) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0044JobInfoObjectList) DeepCopy() *V0044JobInfoObjectList {
	out := new(V0044JobInfoObjectList)
	out.Items = make([]V0044JobInfo, len(o.Items))
	for i, item := range o.Items {
		out.Items[i] = *item.DeepCopy()
	}
	return out
}

var _ object.ObjectList = (*V0044JobInfoObjectList)(nil)

const ObjectTypeV0044Node object.ObjectType = "V0044Node"

func (o *V0044Node) GetType() object.ObjectType {
	return ObjectTypeV0044Node
}

func (o *V0044Node) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0044Node) DeepCopy() *V0044Node {
	return utils.Clone(o)
}

func (o *V0044Node) GetKey() object.ObjectKey {
	return object.ObjectKey(ptr.Deref(o.Name, ""))
}

var _ object.Object = (*V0044Node)(nil)

type V0044NodeObjectList struct {
	Items []V0044Node
}

func (o *V0044NodeObjectList) GetType() object.ObjectType {
	return ObjectTypeV0044Node
}

func (o *V0044NodeObjectList) GetItems() []object.Object {
	list := make([]object.Object, len(o.Items))
	for i, item := range o.Items {
		list[i] = item.DeepCopy()
	}
	return list
}

func (o *V0044NodeObjectList) AppendItem(obj object.Object) {
	item, ok := obj.(*V0044Node)
	if !ok {
		return
	}
	o.Items = append(o.Items, *item.DeepCopy())
}

func (o *V0044NodeObjectList) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0044NodeObjectList) DeepCopy() *V0044NodeObjectList {
	out := new(V0044NodeObjectList)
	out.Items = make([]V0044Node, len(o.Items))
	for i, item := range o.Items {
		out.Items[i] = *item.DeepCopy()
	}
	return out
}

var _ object.ObjectList = (*V0044NodeObjectList)(nil)

// V0044NodeResourceLayoutList is a type alias; must use new type pattern to define methods.
type V0044NodeResourceLayoutListObject V0044NodeResourceLayoutList

const ObjectTypeV0044NodeResourceLayoutList object.ObjectType = "V0044NodeResourceLayoutList"

func (o *V0044NodeResourceLayoutListObject) GetType() object.ObjectType {
	return ObjectTypeV0044NodeResourceLayoutList
}

func (o *V0044NodeResourceLayoutListObject) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0044NodeResourceLayoutListObject) DeepCopy() *V0044NodeResourceLayoutListObject {
	return utils.Clone(o)
}

// The response field is a collection; no valid key.
func (o *V0044NodeResourceLayoutListObject) GetKey() object.ObjectKey {
	return "0"
}

var _ object.Object = (*V0044NodeResourceLayoutListObject)(nil)

type V0044NodeResourceLayoutListObjectList struct {
	Items []V0044NodeResourceLayoutListObject
}

func (o *V0044NodeResourceLayoutListObjectList) GetType() object.ObjectType {
	return ObjectTypeV0044NodeResourceLayoutList
}

func (o *V0044NodeResourceLayoutListObjectList) GetItems() []object.Object {
	list := make([]object.Object, len(o.Items))
	for i, item := range o.Items {
		list[i] = item.DeepCopy()
	}
	return list
}

func (o *V0044NodeResourceLayoutListObjectList) AppendItem(obj object.Object) {
	item, ok := obj.(*V0044NodeResourceLayoutListObject)
	if !ok {
		return
	}
	o.Items = append(o.Items, *item.DeepCopy())
}

func (o *V0044NodeResourceLayoutListObjectList) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0044NodeResourceLayoutListObjectList) DeepCopy() *V0044NodeResourceLayoutListObjectList {
	out := new(V0044NodeResourceLayoutListObjectList)
	out.Items = make([]V0044NodeResourceLayoutListObject, len(o.Items))
	for i, item := range o.Items {
		out.Items[i] = *item.DeepCopy()
	}
	return out
}

var _ object.ObjectList = (*V0044NodeResourceLayoutListObjectList)(nil)

const ObjectTypeV0044PartitionInfo object.ObjectType = "V0044PartitionInfo"

func (o *V0044PartitionInfo) GetType() object.ObjectType {
	return ObjectTypeV0044PartitionInfo
}

func (o *V0044PartitionInfo) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0044PartitionInfo) DeepCopy() *V0044PartitionInfo {
	return utils.Clone(o)
}

func (o *V0044PartitionInfo) GetKey() object.ObjectKey {
	return object.ObjectKey(ptr.Deref(o.Name, ""))
}

var _ object.Object = (*V0044PartitionInfo)(nil)

type V0044PartitionInfoObjectList struct {
	Items []V0044PartitionInfo
}

func (o *V0044PartitionInfoObjectList) GetType() object.ObjectType {
	return ObjectTypeV0044PartitionInfo
}

func (o *V0044PartitionInfoObjectList) GetItems() []object.Object {
	list := make([]object.Object, len(o.Items))
	for i, item := range o.Items {
		list[i] = item.DeepCopy()
	}
	return list
}

func (o *V0044PartitionInfoObjectList) AppendItem(obj object.Object) {
	item, ok := obj.(*V0044PartitionInfo)
	if !ok {
		return
	}
	o.Items = append(o.Items, *item.DeepCopy())
}

func (o *V0044PartitionInfoObjectList) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0044PartitionInfoObjectList) DeepCopy() *V0044PartitionInfoObjectList {
	out := new(V0044PartitionInfoObjectList)
	out.Items = make([]V0044PartitionInfo, len(o.Items))
	for i, item := range o.Items {
		out.Items[i] = *item.DeepCopy()
	}
	return out
}

var _ object.ObjectList = (*V0044PartitionInfoObjectList)(nil)

const ObjectTypeV0044ReservationInfo object.ObjectType = "V0044ReservationInfo"

func (o *V0044ReservationInfo) GetType() object.ObjectType {
	return ObjectTypeV0044ReservationInfo
}

func (o *V0044ReservationInfo) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0044ReservationInfo) DeepCopy() *V0044ReservationInfo {
	return utils.Clone(o)
}

func (o *V0044ReservationInfo) GetKey() object.ObjectKey {
	return object.ObjectKey(ptr.Deref(o.Name, ""))
}

var _ object.Object = (*V0044ReservationInfo)(nil)

type V0044ReservationInfoObjectList struct {
	Items []V0044ReservationInfo
}

func (o *V0044ReservationInfoObjectList) GetType() object.ObjectType {
	return ObjectTypeV0044ReservationInfo
}

func (o *V0044ReservationInfoObjectList) GetItems() []object.Object {
	list := make([]object.Object, len(o.Items))
	for i, item := range o.Items {
		list[i] = item.DeepCopy()
	}
	return list
}

func (o *V0044ReservationInfoObjectList) AppendItem(obj object.Object) {
	item, ok := obj.(*V0044ReservationInfo)
	if !ok {
		return
	}
	o.Items = append(o.Items, *item.DeepCopy())
}

func (o *V0044ReservationInfoObjectList) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0044ReservationInfoObjectList) DeepCopy() *V0044ReservationInfoObjectList {
	out := new(V0044ReservationInfoObjectList)
	out.Items = make([]V0044ReservationInfo, len(o.Items))
	for i, item := range o.Items {
		out.Items[i] = *item.DeepCopy()
	}
	return out
}

var _ object.ObjectList = (*V0044ReservationInfoObjectList)(nil)

const ObjectTypeV0044StatsMsg object.ObjectType = "V0044StatsMsg"

func (o *V0044StatsMsg) GetType() object.ObjectType {
	return ObjectTypeV0044StatsMsg
}

func (o *V0044StatsMsg) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0044StatsMsg) DeepCopy() *V0044StatsMsg {
	return utils.Clone(o)
}

func (o *V0044StatsMsg) GetKey() object.ObjectKey {
	return ""
}

var _ object.Object = (*V0044StatsMsg)(nil)

type V0044StatsMsgObjectList struct {
	Items []V0044StatsMsg
}

func (o *V0044StatsMsgObjectList) GetType() object.ObjectType {
	return ObjectTypeV0044StatsMsg
}

func (o *V0044StatsMsgObjectList) GetItems() []object.Object {
	list := make([]object.Object, len(o.Items))
	for i, item := range o.Items {
		list[i] = item.DeepCopy()
	}
	return list
}

func (o *V0044StatsMsgObjectList) AppendItem(obj object.Object) {
	item, ok := obj.(*V0044StatsMsg)
	if !ok {
		return
	}
	o.Items = append(o.Items, *item.DeepCopy())
}

func (o *V0044StatsMsgObjectList) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0044StatsMsgObjectList) DeepCopy() *V0044StatsMsgObjectList {
	out := new(V0044StatsMsgObjectList)
	out.Items = make([]V0044StatsMsg, len(o.Items))
	for i, item := range o.Items {
		out.Items[i] = *item.DeepCopy()
	}
	return out
}

var _ object.ObjectList = (*V0044StatsMsgObjectList)(nil)
