// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
//
// pkg/object methods for the models in slurm.gen.go.
package v0045

import (
	"fmt"
	"strconv"

	"k8s.io/utils/ptr"

	"github.com/SlinkyProject/slurm-client/pkg/object"
	"github.com/SlinkyProject/slurm-client/pkg/utils"
)

const ObjectTypeV0045ControllerPing object.ObjectType = "V0045ControllerPing"

func (o *V0045ControllerPing) GetType() object.ObjectType {
	return ObjectTypeV0045ControllerPing
}

func (o *V0045ControllerPing) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0045ControllerPing) DeepCopy() *V0045ControllerPing {
	return utils.Clone(o)
}

func (o *V0045ControllerPing) GetKey() object.ObjectKey {
	return object.ObjectKey(ptr.Deref(o.Hostname, ""))
}

func (o *V0045ControllerPing) SetKey(key object.ObjectKey) error {
	o.Hostname = ptr.To(string(key))
	return nil
}

var _ object.Object = (*V0045ControllerPing)(nil)

type V0045ControllerPingObjectList struct {
	Items []V0045ControllerPing
}

func (o *V0045ControllerPingObjectList) GetType() object.ObjectType {
	return ObjectTypeV0045ControllerPing
}

func (o *V0045ControllerPingObjectList) GetItems() []object.Object {
	list := make([]object.Object, len(o.Items))
	for i, item := range o.Items {
		list[i] = item.DeepCopy()
	}
	return list
}

func (o *V0045ControllerPingObjectList) AppendItem(obj object.Object) {
	item, ok := obj.(*V0045ControllerPing)
	if !ok {
		return
	}
	o.Items = append(o.Items, *item.DeepCopy())
}

func (o *V0045ControllerPingObjectList) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0045ControllerPingObjectList) DeepCopy() *V0045ControllerPingObjectList {
	out := new(V0045ControllerPingObjectList)
	out.Items = make([]V0045ControllerPing, len(o.Items))
	for i, item := range o.Items {
		out.Items[i] = *item.DeepCopy()
	}
	return out
}

var _ object.ObjectList = (*V0045ControllerPingObjectList)(nil)

const ObjectTypeV0045JobInfo object.ObjectType = "V0045JobInfo"

func (o *V0045JobInfo) GetType() object.ObjectType {
	return ObjectTypeV0045JobInfo
}

func (o *V0045JobInfo) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0045JobInfo) DeepCopy() *V0045JobInfo {
	return utils.Clone(o)
}

func (o *V0045JobInfo) GetKey() object.ObjectKey {
	return object.ObjectKey(strconv.Itoa(int(ptr.Deref(o.JobId, 0))))
}

func (o *V0045JobInfo) SetKey(key object.ObjectKey) error {
	id, err := strconv.ParseInt(string(key), 10, 32)
	if err != nil {
		return fmt.Errorf("invalid job key %q: %w", key, err)
	}
	o.JobId = ptr.To(int32(id))
	return nil
}

var _ object.Object = (*V0045JobInfo)(nil)

type V0045JobInfoObjectList struct {
	Items []V0045JobInfo
}

func (o *V0045JobInfoObjectList) GetType() object.ObjectType {
	return ObjectTypeV0045JobInfo
}

func (o *V0045JobInfoObjectList) GetItems() []object.Object {
	list := make([]object.Object, len(o.Items))
	for i, item := range o.Items {
		list[i] = item.DeepCopy()
	}
	return list
}

func (o *V0045JobInfoObjectList) AppendItem(obj object.Object) {
	item, ok := obj.(*V0045JobInfo)
	if !ok {
		return
	}
	o.Items = append(o.Items, *item.DeepCopy())
}

func (o *V0045JobInfoObjectList) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0045JobInfoObjectList) DeepCopy() *V0045JobInfoObjectList {
	out := new(V0045JobInfoObjectList)
	out.Items = make([]V0045JobInfo, len(o.Items))
	for i, item := range o.Items {
		out.Items[i] = *item.DeepCopy()
	}
	return out
}

var _ object.ObjectList = (*V0045JobInfoObjectList)(nil)

const ObjectTypeV0045Node object.ObjectType = "V0045Node"

func (o *V0045Node) GetType() object.ObjectType {
	return ObjectTypeV0045Node
}

func (o *V0045Node) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0045Node) DeepCopy() *V0045Node {
	return utils.Clone(o)
}

func (o *V0045Node) GetKey() object.ObjectKey {
	return object.ObjectKey(ptr.Deref(o.Name, ""))
}

func (o *V0045Node) SetKey(key object.ObjectKey) error {
	o.Name = ptr.To(string(key))
	return nil
}

var _ object.Object = (*V0045Node)(nil)

type V0045NodeObjectList struct {
	Items []V0045Node
}

func (o *V0045NodeObjectList) GetType() object.ObjectType {
	return ObjectTypeV0045Node
}

func (o *V0045NodeObjectList) GetItems() []object.Object {
	list := make([]object.Object, len(o.Items))
	for i, item := range o.Items {
		list[i] = item.DeepCopy()
	}
	return list
}

func (o *V0045NodeObjectList) AppendItem(obj object.Object) {
	item, ok := obj.(*V0045Node)
	if !ok {
		return
	}
	o.Items = append(o.Items, *item.DeepCopy())
}

func (o *V0045NodeObjectList) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0045NodeObjectList) DeepCopy() *V0045NodeObjectList {
	out := new(V0045NodeObjectList)
	out.Items = make([]V0045Node, len(o.Items))
	for i, item := range o.Items {
		out.Items[i] = *item.DeepCopy()
	}
	return out
}

var _ object.ObjectList = (*V0045NodeObjectList)(nil)

// V0045NodeResourceLayoutList is a type alias; must use new type pattern to define methods.
type V0045NodeResourceLayoutListObject V0045NodeResourceLayoutList

const ObjectTypeV0045NodeResourceLayoutList object.ObjectType = "V0045NodeResourceLayoutList"

func (o *V0045NodeResourceLayoutListObject) GetType() object.ObjectType {
	return ObjectTypeV0045NodeResourceLayoutList
}

func (o *V0045NodeResourceLayoutListObject) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0045NodeResourceLayoutListObject) DeepCopy() *V0045NodeResourceLayoutListObject {
	return utils.Clone(o)
}

// The response field is a collection; no valid key.
func (o *V0045NodeResourceLayoutListObject) GetKey() object.ObjectKey {
	return "0"
}

func (o *V0045NodeResourceLayoutListObject) SetKey(key object.ObjectKey) error {
	if key != o.GetKey() {
		return fmt.Errorf("%s has a fixed key %q", o.GetType(), o.GetKey())
	}
	return nil
}

var _ object.Object = (*V0045NodeResourceLayoutListObject)(nil)

type V0045NodeResourceLayoutListObjectList struct {
	Items []V0045NodeResourceLayoutListObject
}

func (o *V0045NodeResourceLayoutListObjectList) GetType() object.ObjectType {
	return ObjectTypeV0045NodeResourceLayoutList
}

func (o *V0045NodeResourceLayoutListObjectList) GetItems() []object.Object {
	list := make([]object.Object, len(o.Items))
	for i, item := range o.Items {
		list[i] = item.DeepCopy()
	}
	return list
}

func (o *V0045NodeResourceLayoutListObjectList) AppendItem(obj object.Object) {
	item, ok := obj.(*V0045NodeResourceLayoutListObject)
	if !ok {
		return
	}
	o.Items = append(o.Items, *item.DeepCopy())
}

func (o *V0045NodeResourceLayoutListObjectList) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0045NodeResourceLayoutListObjectList) DeepCopy() *V0045NodeResourceLayoutListObjectList {
	out := new(V0045NodeResourceLayoutListObjectList)
	out.Items = make([]V0045NodeResourceLayoutListObject, len(o.Items))
	for i, item := range o.Items {
		out.Items[i] = *item.DeepCopy()
	}
	return out
}

var _ object.ObjectList = (*V0045NodeResourceLayoutListObjectList)(nil)

const ObjectTypeV0045PartitionInfo object.ObjectType = "V0045PartitionInfo"

func (o *V0045PartitionInfo) GetType() object.ObjectType {
	return ObjectTypeV0045PartitionInfo
}

func (o *V0045PartitionInfo) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0045PartitionInfo) DeepCopy() *V0045PartitionInfo {
	return utils.Clone(o)
}

func (o *V0045PartitionInfo) GetKey() object.ObjectKey {
	return object.ObjectKey(ptr.Deref(o.Name, ""))
}

func (o *V0045PartitionInfo) SetKey(key object.ObjectKey) error {
	o.Name = ptr.To(string(key))
	return nil
}

var _ object.Object = (*V0045PartitionInfo)(nil)

type V0045PartitionInfoObjectList struct {
	Items []V0045PartitionInfo
}

func (o *V0045PartitionInfoObjectList) GetType() object.ObjectType {
	return ObjectTypeV0045PartitionInfo
}

func (o *V0045PartitionInfoObjectList) GetItems() []object.Object {
	list := make([]object.Object, len(o.Items))
	for i, item := range o.Items {
		list[i] = item.DeepCopy()
	}
	return list
}

func (o *V0045PartitionInfoObjectList) AppendItem(obj object.Object) {
	item, ok := obj.(*V0045PartitionInfo)
	if !ok {
		return
	}
	o.Items = append(o.Items, *item.DeepCopy())
}

func (o *V0045PartitionInfoObjectList) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0045PartitionInfoObjectList) DeepCopy() *V0045PartitionInfoObjectList {
	out := new(V0045PartitionInfoObjectList)
	out.Items = make([]V0045PartitionInfo, len(o.Items))
	for i, item := range o.Items {
		out.Items[i] = *item.DeepCopy()
	}
	return out
}

var _ object.ObjectList = (*V0045PartitionInfoObjectList)(nil)

const ObjectTypeV0045ReservationInfo object.ObjectType = "V0045ReservationInfo"

func (o *V0045ReservationInfo) GetType() object.ObjectType {
	return ObjectTypeV0045ReservationInfo
}

func (o *V0045ReservationInfo) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0045ReservationInfo) DeepCopy() *V0045ReservationInfo {
	return utils.Clone(o)
}

func (o *V0045ReservationInfo) GetKey() object.ObjectKey {
	return object.ObjectKey(ptr.Deref(o.Name, ""))
}

func (o *V0045ReservationInfo) SetKey(key object.ObjectKey) error {
	o.Name = ptr.To(string(key))
	return nil
}

var _ object.Object = (*V0045ReservationInfo)(nil)

type V0045ReservationInfoObjectList struct {
	Items []V0045ReservationInfo
}

func (o *V0045ReservationInfoObjectList) GetType() object.ObjectType {
	return ObjectTypeV0045ReservationInfo
}

func (o *V0045ReservationInfoObjectList) GetItems() []object.Object {
	list := make([]object.Object, len(o.Items))
	for i, item := range o.Items {
		list[i] = item.DeepCopy()
	}
	return list
}

func (o *V0045ReservationInfoObjectList) AppendItem(obj object.Object) {
	item, ok := obj.(*V0045ReservationInfo)
	if !ok {
		return
	}
	o.Items = append(o.Items, *item.DeepCopy())
}

func (o *V0045ReservationInfoObjectList) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0045ReservationInfoObjectList) DeepCopy() *V0045ReservationInfoObjectList {
	out := new(V0045ReservationInfoObjectList)
	out.Items = make([]V0045ReservationInfo, len(o.Items))
	for i, item := range o.Items {
		out.Items[i] = *item.DeepCopy()
	}
	return out
}

var _ object.ObjectList = (*V0045ReservationInfoObjectList)(nil)

const ObjectTypeV0045StatsMsg object.ObjectType = "V0045StatsMsg"

func (o *V0045StatsMsg) GetType() object.ObjectType {
	return ObjectTypeV0045StatsMsg
}

func (o *V0045StatsMsg) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0045StatsMsg) DeepCopy() *V0045StatsMsg {
	return utils.Clone(o)
}

func (o *V0045StatsMsg) GetKey() object.ObjectKey {
	return ""
}

func (o *V0045StatsMsg) SetKey(key object.ObjectKey) error {
	if key != o.GetKey() {
		return fmt.Errorf("%s has a fixed key %q", o.GetType(), o.GetKey())
	}
	return nil
}

var _ object.Object = (*V0045StatsMsg)(nil)

type V0045StatsMsgObjectList struct {
	Items []V0045StatsMsg
}

func (o *V0045StatsMsgObjectList) GetType() object.ObjectType {
	return ObjectTypeV0045StatsMsg
}

func (o *V0045StatsMsgObjectList) GetItems() []object.Object {
	list := make([]object.Object, len(o.Items))
	for i, item := range o.Items {
		list[i] = item.DeepCopy()
	}
	return list
}

func (o *V0045StatsMsgObjectList) AppendItem(obj object.Object) {
	item, ok := obj.(*V0045StatsMsg)
	if !ok {
		return
	}
	o.Items = append(o.Items, *item.DeepCopy())
}

func (o *V0045StatsMsgObjectList) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0045StatsMsgObjectList) DeepCopy() *V0045StatsMsgObjectList {
	out := new(V0045StatsMsgObjectList)
	out.Items = make([]V0045StatsMsg, len(o.Items))
	for i, item := range o.Items {
		out.Items[i] = *item.DeepCopy()
	}
	return out
}

var _ object.ObjectList = (*V0045StatsMsgObjectList)(nil)
