// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
//
// pkg/object methods for the models in slurm.gen.go.
package v0043

import (
	"strconv"

	"k8s.io/utils/ptr"

	"github.com/SlinkyProject/slurm-client/pkg/object"
	"github.com/SlinkyProject/slurm-client/pkg/utils"
)

const ObjectTypeV0043ControllerPing object.ObjectType = "V0043ControllerPing"

func (o *V0043ControllerPing) GetType() object.ObjectType {
	return ObjectTypeV0043ControllerPing
}

func (o *V0043ControllerPing) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0043ControllerPing) DeepCopy() *V0043ControllerPing {
	return utils.Clone(o)
}

func (o *V0043ControllerPing) GetKey() object.ObjectKey {
	return object.ObjectKey(ptr.Deref(o.Hostname, ""))
}

var _ object.Object = (*V0043ControllerPing)(nil)

type V0043ControllerPingObjectList struct {
	Items []V0043ControllerPing
}

func (o *V0043ControllerPingObjectList) GetType() object.ObjectType {
	return ObjectTypeV0043ControllerPing
}

func (o *V0043ControllerPingObjectList) GetItems() []object.Object {
	list := make([]object.Object, len(o.Items))
	for i, item := range o.Items {
		list[i] = item.DeepCopy()
	}
	return list
}

func (o *V0043ControllerPingObjectList) AppendItem(obj object.Object) {
	item, ok := obj.(*V0043ControllerPing)
	if !ok {
		return
	}
	o.Items = append(o.Items, *item.DeepCopy())
}

func (o *V0043ControllerPingObjectList) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0043ControllerPingObjectList) DeepCopy() *V0043ControllerPingObjectList {
	out := new(V0043ControllerPingObjectList)
	out.Items = make([]V0043ControllerPing, len(o.Items))
	for i, item := range o.Items {
		out.Items[i] = *item.DeepCopy()
	}
	return out
}

var _ object.ObjectList = (*V0043ControllerPingObjectList)(nil)

const ObjectTypeV0043JobInfo object.ObjectType = "V0043JobInfo"

func (o *V0043JobInfo) GetType() object.ObjectType {
	return ObjectTypeV0043JobInfo
}

func (o *V0043JobInfo) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0043JobInfo) DeepCopy() *V0043JobInfo {
	return utils.Clone(o)
}

func (o *V0043JobInfo) GetKey() object.ObjectKey {
	return object.ObjectKey(strconv.Itoa(int(ptr.Deref(o.JobId, 0))))
}

var _ object.Object = (*V0043JobInfo)(nil)

type V0043JobInfoObjectList struct {
	Items []V0043JobInfo
}

func (o *V0043JobInfoObjectList) GetType() object.ObjectType {
	return ObjectTypeV0043JobInfo
}

func (o *V0043JobInfoObjectList) GetItems() []object.Object {
	list := make([]object.Object, len(o.Items))
	for i, item := range o.Items {
		list[i] = item.DeepCopy()
	}
	return list
}

func (o *V0043JobInfoObjectList) AppendItem(obj object.Object) {
	item, ok := obj.(*V0043JobInfo)
	if !ok {
		return
	}
	o.Items = append(o.Items, *item.DeepCopy())
}

func (o *V0043JobInfoObjectList) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0043JobInfoObjectList) DeepCopy() *V0043JobInfoObjectList {
	out := new(V0043JobInfoObjectList)
	out.Items = make([]V0043JobInfo, len(o.Items))
	for i, item := range o.Items {
		out.Items[i] = *item.DeepCopy()
	}
	return out
}

var _ object.ObjectList = (*V0043JobInfoObjectList)(nil)

const ObjectTypeV0043Node object.ObjectType = "V0043Node"

func (o *V0043Node) GetType() object.ObjectType {
	return ObjectTypeV0043Node
}

func (o *V0043Node) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0043Node) DeepCopy() *V0043Node {
	return utils.Clone(o)
}

func (o *V0043Node) GetKey() object.ObjectKey {
	return object.ObjectKey(ptr.Deref(o.Name, ""))
}

var _ object.Object = (*V0043Node)(nil)

type V0043NodeObjectList struct {
	Items []V0043Node
}

func (o *V0043NodeObjectList) GetType() object.ObjectType {
	return ObjectTypeV0043Node
}

func (o *V0043NodeObjectList) GetItems() []object.Object {
	list := make([]object.Object, len(o.Items))
	for i, item := range o.Items {
		list[i] = item.DeepCopy()
	}
	return list
}

func (o *V0043NodeObjectList) AppendItem(obj object.Object) {
	item, ok := obj.(*V0043Node)
	if !ok {
		return
	}
	o.Items = append(o.Items, *item.DeepCopy())
}

func (o *V0043NodeObjectList) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0043NodeObjectList) DeepCopy() *V0043NodeObjectList {
	out := new(V0043NodeObjectList)
	out.Items = make([]V0043Node, len(o.Items))
	for i, item := range o.Items {
		out.Items[i] = *item.DeepCopy()
	}
	return out
}

var _ object.ObjectList = (*V0043NodeObjectList)(nil)

const ObjectTypeV0043PartitionInfo object.ObjectType = "V0043PartitionInfo"

func (o *V0043PartitionInfo) GetType() object.ObjectType {
	return ObjectTypeV0043PartitionInfo
}

func (o *V0043PartitionInfo) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0043PartitionInfo) DeepCopy() *V0043PartitionInfo {
	return utils.Clone(o)
}

func (o *V0043PartitionInfo) GetKey() object.ObjectKey {
	return object.ObjectKey(ptr.Deref(o.Name, ""))
}

var _ object.Object = (*V0043PartitionInfo)(nil)

type V0043PartitionInfoObjectList struct {
	Items []V0043PartitionInfo
}

func (o *V0043PartitionInfoObjectList) GetType() object.ObjectType {
	return ObjectTypeV0043PartitionInfo
}

func (o *V0043PartitionInfoObjectList) GetItems() []object.Object {
	list := make([]object.Object, len(o.Items))
	for i, item := range o.Items {
		list[i] = item.DeepCopy()
	}
	return list
}

func (o *V0043PartitionInfoObjectList) AppendItem(obj object.Object) {
	item, ok := obj.(*V0043PartitionInfo)
	if !ok {
		return
	}
	o.Items = append(o.Items, *item.DeepCopy())
}

func (o *V0043PartitionInfoObjectList) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0043PartitionInfoObjectList) DeepCopy() *V0043PartitionInfoObjectList {
	out := new(V0043PartitionInfoObjectList)
	out.Items = make([]V0043PartitionInfo, len(o.Items))
	for i, item := range o.Items {
		out.Items[i] = *item.DeepCopy()
	}
	return out
}

var _ object.ObjectList = (*V0043PartitionInfoObjectList)(nil)

const ObjectTypeV0043ReservationInfo object.ObjectType = "V0043ReservationInfo"

func (o *V0043ReservationInfo) GetType() object.ObjectType {
	return ObjectTypeV0043ReservationInfo
}

func (o *V0043ReservationInfo) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0043ReservationInfo) DeepCopy() *V0043ReservationInfo {
	return utils.Clone(o)
}

func (o *V0043ReservationInfo) GetKey() object.ObjectKey {
	return object.ObjectKey(ptr.Deref(o.Name, ""))
}

var _ object.Object = (*V0043ReservationInfo)(nil)

type V0043ReservationInfoObjectList struct {
	Items []V0043ReservationInfo
}

func (o *V0043ReservationInfoObjectList) GetType() object.ObjectType {
	return ObjectTypeV0043ReservationInfo
}

func (o *V0043ReservationInfoObjectList) GetItems() []object.Object {
	list := make([]object.Object, len(o.Items))
	for i, item := range o.Items {
		list[i] = item.DeepCopy()
	}
	return list
}

func (o *V0043ReservationInfoObjectList) AppendItem(obj object.Object) {
	item, ok := obj.(*V0043ReservationInfo)
	if !ok {
		return
	}
	o.Items = append(o.Items, *item.DeepCopy())
}

func (o *V0043ReservationInfoObjectList) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0043ReservationInfoObjectList) DeepCopy() *V0043ReservationInfoObjectList {
	out := new(V0043ReservationInfoObjectList)
	out.Items = make([]V0043ReservationInfo, len(o.Items))
	for i, item := range o.Items {
		out.Items[i] = *item.DeepCopy()
	}
	return out
}

var _ object.ObjectList = (*V0043ReservationInfoObjectList)(nil)

const ObjectTypeV0043StatsMsg object.ObjectType = "V0043StatsMsg"

func (o *V0043StatsMsg) GetType() object.ObjectType {
	return ObjectTypeV0043StatsMsg
}

func (o *V0043StatsMsg) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0043StatsMsg) DeepCopy() *V0043StatsMsg {
	return utils.Clone(o)
}

func (o *V0043StatsMsg) GetKey() object.ObjectKey {
	return ""
}

var _ object.Object = (*V0043StatsMsg)(nil)

type V0043StatsMsgObjectList struct {
	Items []V0043StatsMsg
}

func (o *V0043StatsMsgObjectList) GetType() object.ObjectType {
	return ObjectTypeV0043StatsMsg
}

func (o *V0043StatsMsgObjectList) GetItems() []object.Object {
	list := make([]object.Object, len(o.Items))
	for i, item := range o.Items {
		list[i] = item.DeepCopy()
	}
	return list
}

func (o *V0043StatsMsgObjectList) AppendItem(obj object.Object) {
	item, ok := obj.(*V0043StatsMsg)
	if !ok {
		return
	}
	o.Items = append(o.Items, *item.DeepCopy())
}

func (o *V0043StatsMsgObjectList) DeepCopyObject() object.RuntimeObject {
	return o.DeepCopy()
}

func (o *V0043StatsMsgObjectList) DeepCopy() *V0043StatsMsgObjectList {
	out := new(V0043StatsMsgObjectList)
	out.Items = make([]V0043StatsMsg, len(o.Items))
	for i, item := range o.Items {
		out.Items[i] = *item.DeepCopy()
	}
	return out
}

var _ object.ObjectList = (*V0043StatsMsgObjectList)(nil)
