---
# SPDX-FileCopyrightText: Copyright (C) SchedMD LLC.
# SPDX-License-Identifier: Apache-2.0

services:
  database:
    image: docker.io/mariadb:latest
    container_name: mariadb
    hostname: mariadb
    restart: unless-stopped
    # ports:
    #   - 13306:3306
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
    networks:
      - default
    healthcheck:
      test: [CMD, healthcheck.sh, --connect, --innodb_initialized]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
  accounting:
    image: ghcr.io/slinkyproject/slurmdbd:25.05-ubuntu24.04
    container_name: slurmdbd
    hostname: slurmdbd
    entrypoint: /opt/entrypoint/slurmdbd.sh
    restart: unless-stopped
    # ports:
    #   - 16819:6819
    healthcheck:
      test: [CMD-SHELL, bash, sacctmgr, ping]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./compose/etc/:/opt/etc/slurm/:ro
      - ./compose/entrypoint/:/opt/entrypoint/:ro
    networks:
      - default
    depends_on:
      database:
        condition: service_healthy
  control-plane:
    image: ghcr.io/slinkyproject/slurmctld:25.05-ubuntu24.04
    container_name: slurmctld
    hostname: slurmctld
    entrypoint: /opt/entrypoint/slurmctld.sh
    restart: unless-stopped
    # ports:
    #   - 16817:6817
    healthcheck:
      test: [CMD-SHELL, bash, scontrol, ping]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./compose/etc/:/opt/etc/slurm/:ro
      - ./compose/entrypoint/:/opt/entrypoint/:ro
    networks:
      - default
    depends_on:
      accounting:
        condition: service_healthy
  compute:
    image: ghcr.io/slinkyproject/slurmd:25.05-ubuntu24.04
    container_name: slurmd
    hostname: slurmd
    entrypoint: /opt/entrypoint/slurmd.sh
    restart: unless-stopped
    # ports:
    #   - 16818:6818
    healthcheck:
      test: [CMD-SHELL, bash, scontrol, show, slurmd]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./compose/etc/:/opt/etc/slurm/:ro
      - ./compose/entrypoint/:/opt/entrypoint/:ro
    networks:
      - default
    depends_on:
      control-plane:
        condition: service_healthy
  restapi:
    image: ghcr.io/slinkyproject/slurmrestd:25.05-ubuntu24.04
    container_name: slurmrestd
    hostname: slurmrestd
    environment:
      - SLURMRESTD_SECURITY=disable_unshare_files,disable_unshare_sysv
    entrypoint: /opt/entrypoint/slurmrestd.sh
    restart: unless-stopped
    ports:
      - 16820:6820
    volumes:
      - ./compose/etc/:/opt/etc/slurm/:ro
      - ./compose/entrypoint/:/opt/entrypoint/:ro
    networks:
      - default
    depends_on:
      control-plane:
        condition: service_healthy
      accounting:
        condition: service_healthy
  authcred:
    image: ghcr.io/slinkyproject/sackd:25.05-ubuntu24.04
    container_name: sackd
    hostname: sackd
    entrypoint: /opt/entrypoint/sackd.sh
    restart: unless-stopped
    healthcheck:
      test: [CMD-SHELL, bash, scontrol, ping]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./compose/etc/:/opt/etc/slurm/:ro
      - ./compose/entrypoint/:/opt/entrypoint/:ro
    networks:
      - default
    depends_on:
      control-plane:
        condition: service_healthy
networks:
  default:
    driver: bridge
